# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          sudo apt-get install -y proj-bin
          python -m pip install --upgrade pip
          pip install
      - name: Test
        run: |
          python setup.py test
